name: MobCaptains
author: PuckiSilver
version: v3.4.0
output: build
require:
  - bolt

data_pack:
  load:
    - libs/lantern-load.zip
    - src
  name: MobCaptains
  description: Rare and strong mobs with custom loot
  pack_format: 81
  supported_formats: [48, 81]
  min_format: 48
  max_format: 90

pipeline:
  - mecha
  - plugins.remove_empty_functions
  - plugins.credit
meta:
  credit: [ps-mob]
